[workspace]
members = [
  "package",
]

[package]
name = "scie-jump"
version = "0.1.0"
description = "The self contained interpreted executable launcher."
authors = [
  "John Sirois <john.sirois@gmail.com>",
]
edition = "2021"
publish = false

[profile.release]
opt-level = "s"
strip = "symbols"
lto = "thin"

# N.B.: The `package` psuedo-crate serves as a cross-platform build-step
# to post-process this root crate's binary by adding a 64 bit magic
# trailer to the binary that allows it to know its own size and know if
# it's being run as a stub or an application. This ensures when its
# binary dependency (this root crate) is built, it is size-optimized and
# has symbols stripped. The lto can't be applied to a build script, but
# that is properly plumbed to the root crate during a `-p package`
# build.
[profile.release.build-override]
opt-level = "s"
strip = "symbols"

[dependencies]
jump = { path = "jump" }
nix = "0.25"
proc-exit = "2.0"
