[package]
name = "scie-jump"
version = "0.1.0"
description = "The self contained interpreted executable launcher."
authors = [
  "John Sirois <john.sirois@gmail.com>",
]
edition = "2021"
publish = false

[lib]
name = "scie_jump"
path = "src/lib.rs"

[[bin]]
name = "scie-jump"
path = "src/main.rs"

[profile.release]
opt-level = "s"
strip = "symbols"
lto = "thin"

[dependencies]
async-compression = { version = "0.3", features = ["futures-io", "all-algorithms"] }
bstr = "1.0"
dirs = "4.0"
fd-lock = "3.0"
itertools = "0.10"
lazy_static = "1.4"
memmap = "0.7"
nix = "0.25"
proc-exit = "2.0"
regex = "1.6"
relative-path = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structure = "0.1"
tar = "0.4"
tuple = "0.5"
zip = "0.6"
