[package]
name = "jump"
version = "0.1.2"
description = "The bulk of the scie-jump binary logic."
authors = [
    "John Sirois <john.sirois@gmail.com>",
]
edition = "2021"
publish = false

[dependencies]
bstr = { workspace = true }
byteorder = "1.4"
bzip2 = { workspace = true }
dirs = "4.0"
fd-lock = "3.0"
flate2 = { workspace = true }
itertools = "0.10"
log = { workspace = true }
logging_timer = { workspace = true }
memmap = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
structure = "0.1"
tar = { workspace = true }
tuple = "0.5"
xz2 = { workspace = true }
zip = { workspace = true }
zstd = { workspace = true }