[package]
name = "jump"
version = "0.1.0"
description = "The bulk of the scie-jump binary logic."
authors = [
    "John Sirois <john.sirois@gmail.com>",
]
edition = "2021"
publish = false

[dependencies]
bstr = "1.0"
byteorder = "1.4"
bzip2 = "0.4"
dirs = "4.0"
fd-lock = "3.0"
flate2 = "1.0"
itertools = "0.10"
log = { workspace = true }
logging_timer = { workspace = true }
memmap = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
structure = "0.1"
tar = "0.4"
tuple = "0.5"
xz2 = "0.1"
zip = "0.6"
zstd = "0.11"