[package]
name = "package"
version = "0.1.0"
description = "Packages the scie-jump binary into its final form."
authors = [
    "John Sirois <john.sirois@gmail.com>",
]
edition = "2021"
publish = false

[build-dependencies]
byteorder = "1.4"
jump = { path="../jump" }
scie-jump = { path="..", artifact="bin" }

[dependencies]
proc-exit = "2.0"
