name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/') }}
jobs:
  org-check:
    name: Check GitHub Organization
    if: ${{ github.repository_owner == 'a-scie' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Noop
        run: "true"
  ci:
    name: (${{ matrix.os }}) CI
    needs: org-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            python-lift: lift.linux-x86_64.json
            java-lift: lift.linux-x86_64.json
          - os: macos-11
            python-lift: lift.macos-x86_64.json
            java-lift: lift.macos-x86_64.json
          - os: windows-2022
            java-lift: lift.windows-x86_64.json
    steps:
      - uses: actions/checkout@v3
      - name: Check Formatting
        run: cargo fmt --check --all
      - name: Lint
        run: cargo clippy --all
      - name: Test
        run: cargo test --all
      - name: Build
        run: cargo build
      - name: Package
        run: cargo run -p package dist
      - name: Python Example (Pants)
        if: ${{ matrix.lift }}
        run: |
          examples/prepare.sh python
          dist/scie-jump* examples/python/${{ matrix.lift }}
          time RUST_LOG=trace ./pants -V
          time ./pants -V
          SCIE_BOOT=inspect ./pants interpreter --verbose --indent 2
      - name: Java Example (Coursier)
        run: |
          examples/prepare.sh java
          dist/scie-jump* examples/java/${{ matrix.lift }}
          time RUST_LOG=debug ./coursier version
          time ./coursier java-home

