name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to manually run a deploy for.
        required: true
jobs:
  org-check:
    name: Check GitHub Organization
    if: ${{ github.repository_owner == 'a-scie' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Noop
        run: "true"
  determine-tag:
    name: Determine the release tag to operate against.
    needs: org-check
    runs-on: ubuntu-20.04
    outputs:
      release-tag: ${{ steps.determine-tag.outputs.release-tag }}
      release-version: ${{ steps.determine-tag.outputs.release-version }}
    steps:
      - name: Determine Tag
        id: determine-tag
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            RELEASE_TAG=${{ github.event.inputs.tag }}
          else
            RELEASE_TAG=${GITHUB_REF#refs/tags/}
          fi
          if [[ "${RELEASE_TAG}" =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "release-tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
            echo "release-version=${RELEASE_TAG#v}" >> $GITHUB_OUTPUT
          else
            echo "::error::Release tag '${RELEASE_TAG}' must match 'v\d+.\d+.\d+'."
            exit 1
          fi
  github-release:
    name: (${{ matrix.os }}) Create Github Release
    needs: determine-tag
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11, macos-13-aarch64, windows-2022 ]
    environment: Release
    steps:
      - name: Checkout scie-jump ${{ needs.determine-tag.outputs.release-tag }}
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.determine-tag.outputs.release-tag }}
      - name: Package scie-jump ${{ needs.determine-tag.outputs.release-tag }} binary
        run: cargo run --release -p package dist
      - name: Setup Python
        if: ${{ matrix.os != 'macos-13-aarch64' }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Calculate Tox Version
        id: calculate-tox-version
        shell: python
        run: |
          from __future__ import print_function
          import os
          try:
              from ConfigParser import ConfigParser
          except ImportError:
              from configparser import ConfigParser
          cp = ConfigParser()
          cp.read("tox.ini")
          tox_min_version = cp.get("tox", "minversion")
          with open(os.environ["GITHUB_OUTPUT"], "a") as gh_output_fp:
              print("tox-min-version={}".format(tox_min_version), file=gh_output_fp)
      - name: Install Tox
        run: |
          python -mpip install -U pip
          python -mpip install 'tox==${{ steps.calculate-tox-version.outputs.tox-min-version }}'
      - name: Prepare Changelog
        id: prepare-changelog
        run: |
          CHANGELOG="$(tox -echangelog -qq -- ${{ needs.determine-tag.outputs.release-version }})"
          echo "changelog=${CHANGELOG}" >> $GITHUB_OUTPUT
      - name: Create ${{ needs.determine-tag.outputs.release-tag }} Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.determine-tag.outputs.release-tag }}
          name: scie-jump ${{ needs.determine-tag.outputs.release-version }}
          body: |
            ---

            ${{ steps.prepare-changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: dist/scie-jump*
          fail_on_unmatched_files: true
          discussion_category_name: Announcements
  aarch64-release-trigger:
    name: Trigger Circle CI Linux aarch64 Github Release
    needs:
      - determine-tag
      - github-release
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger aarch64 release
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Meta: "${{ needs.determine-tag.outputs.release-tag }}"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
